version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/cypress
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-InLoop-package.json
            - v1-deps-InLoop
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-InLoop-package.json
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: mkdir ~/cypress/reports  
      - cypress/run:
          command: npm run cypress #run custom command to clean reports, run tests, merge and generate reports
      - store_test_results:
          path: ~/cypress/reports
      - store_artifacts:
          path: ~/cypress/artifacts  