# Orb 'cypress-io/cypress@1' resolved to 'cypress-io/cypress@1.13.0'
version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
        working_directory: ''
    - run:
        name: Npm CI
        command: npm ci
        working_directory: ''
    - run:
        name: Verify Cypress
        command: npx cypress verify
        working_directory: ''
    - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - run:
        name: Run Cypress tests
        no_output_timeout: 10m
        command: npx cypress run
        working_directory: '~/cypress'
    - store_artifacts:
        path: videos
    - store_artifacts:
        path: screenshots
    - store_test_results:
        path: reports
workflows:
  build:
    jobs:
    - cypress/run
  version: 2