version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - run: mkdir ~/cypress
      - run: mkdir ~/cypress/reports  
      - cypress/run:
          command: npm run cypress #run custom command to clean reports, run tests, merge and generate reports
      - run:
          command: npm run cypress          
      - store_test_results:
          path: ~/cypress/reports
      - store_artifacts:
          path: ~/cypress/artifacts  