version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/cypress
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests 
          command: npx cypress run --reporter mochawesome --reporter-options reportDir=reports,overwrite=false,html=false,json=true 
      - run:
          name: Merge Mochawesome reports
          command: npx mochawesome-merge ./reports/mochawesome.json>./reports/full_report.json                   
      - run:
          name: Generate Mochawesome reports
          command: npx mochawesome-report-generator ./reports/full_report.json --reportDir ./reports/ --reportFilename full_report.html      
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: reports