# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:

      steps:
        - run:
            name: Run cypress test and generate report
            command: npm run cypress
        - store_artifacts: true
        - store_test_results:
                 path: results
            